package com.example.emily.catnap;

import android.app.Notification;
import android.app.NotificationManager;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.graphics.Color;
import android.support.v4.app.NotificationCompat;

/**
 * Created by emily on 11/4/2017.
 *
 * This class is used in conjunction with Customize.startAlarm() to fire off
 * notifications when the user is using their phone during the specified time
 * interval
 */

public class AlarmReceiver extends BroadcastReceiver {

    /**
     * Upon receipt of a signal generated by the AlarmManager in Customize.startAlarm(),
     * generate a notification which will be sent to the user's phone when they are
     * using it during the user-specified time interval. The NotificationManager and
     * NotificationCompat.Builder objects are used to customize the notification and to
     * fire off notifications when called
     *
     * @param context
     *      The current context of the application
     * @param intent
     *      The intent used to construct the notification
     */
    public void onReceive(Context context, Intent intent ){
        NotificationCompat.Builder builder = new NotificationCompat.Builder(context);
        NotificationManager notificationManager = (NotificationManager) context
                .getSystemService(Context.NOTIFICATION_SERVICE);
        Notification notification;
        notification = builder.setDefaults(Notification.DEFAULT_ALL)
                .setWhen(System.currentTimeMillis())
                .setSmallIcon(R.mipmap.ic_launcher)
                .setAutoCancel(true)
                .setContentTitle("CatNap")
                .setContentText("Sleep Time")
                .setSubText("Turn off your phone (╯°□°）╯︵ ┻━┻")
                .setColor(Color.BLUE)
                .build();
        notificationManager.notify(1, notification);
    }
}
